# Generated by Django 3.0.4 on 2020-04-06 18:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("db", "0001_initial"),
    ]

    operations = [
        migrations.RenameModel(old_name="LandInterest", new_name="PropertyInterest",),
    ]
