# Generated by Django 3.0.7 on 2020-06-12 08:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0004_auto_20200611_1457'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='role',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
