# Generated by Django 3.0.4 on 2020-04-06 22:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("db", "0004_auto_20200406_2143"),
    ]

    operations = [
        migrations.AlterField(
            model_name="giftinterest",
            name="date",
            field=models.DateField(
                blank=True, help_text="Date gift received", null=True
            ),
        ),
    ]
