name: Django CI

on: [push, pull_request]

jobs:
  build:

    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Install Dependencies
      run: |
        docker-compose up -d
        docker-compose exec -T declaration_nav pip install -r /code/requirements_dev.txt
        docker-compose exec -T declaration_nav sh -c 'apt update && apt -y install chromium'
        docker-compose exec -T declaration_nav sh -c 'wget http://chromedriver.storage.googleapis.com/83.0.4103.39/chromedriver_linux64.zip && unzip chromedriver_linux64.zip -d /usr/local/bin'
    - name: Run Tests
      run: |
        docker-compose exec -T declaration_nav sh -c 'CHROME_NO_SANDBOX=True ./manage.py test'
